### ISSUE TITLE
Use modern tools

### ISSUE THREAD

**Issue by DavidJFelix** [tedmiston/sublime_tower_plugin#1]
Sublime -> VSCode
Tower -> GitKraken

😉

**Comment by tedmiston** [comment]
🧐

**Comment by tedmiston** [comment]
```
>>> import sys ; sys.version
'3.3.6 (default, Mar 30 2018, 11:14:15) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]'
```

soul-crushing tho

**Comment by DavidJFelix** [comment]
This wouldn't happen if they ever released a new version of sublime.

**Comment by tedmiston** [comment]
They're putting new releases out (5 this year) but for some reason not updating the python ¯\\_(ツ)_/¯
